# Generated by Django 5.0.1 on 2025-04-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_medicineorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineOrder',
        ),
    ]
